import type { ChapterId, MachineId } from "./types";

export const chapters: { view: ChapterId; anchor: string }[] = [
  { view: "overview", anchor: "system" }, { view: "identify", anchor: "loop" },
  { view: "evaluate", anchor: "permissions" }, { view: "apply", anchor: "release" },
  { view: "record", anchor: "sessions" }, { view: "connect", anchor: "operations" },
  { view: "pilot", anchor: "pilot" },
];
export const machines: MachineId[] = ["table-saw", "bandsaw", "cnc"];
export const docsUrl = (language: "de" | "en", path: string) => `https://docs.attraccess.org/#/${language}/${path}`;

export const workshopCopy = {
  de: {
    chapter: "Station im Werkstattalltag", tour: "Ein Tag in Ihrer Werkstatt", nav: ["Alltag", "Ankommen", "Prüfen", "Nutzen", "Übergeben", "Wartung", "Ihr Start"],
    hero: ["Mehr Werkstatt.", "Weniger Hinterherlaufen."],
    intro: "Späne auf der Säge. Zubehör nicht am Platz. Und wer kümmert sich um die defekte Maschine? Gemeinsam genutzte Ressourcen brauchen mehr als einen Schlüssel.",
    promise: "Attraccess verbindet Einweisungen, kurze Checks, Nutzung und Wartung. Damit der gute Umgang mit Ihrer Ausstattung Teil des Alltags wird, statt ständig eine Erinnerung zu brauchen.",
    explore: "Einen Arbeitstag durchspielen", skip: "Direkt zum Pilot", meet: "Ihre Werkstatt, im Kleinen", duration: "Vom Ankommen bis zur nächsten Person.",
    pain: ["Wer darf an die Säge?", "Wo ist das Zubehör?", "Wer räumt die Späne weg?", "Und wenn etwas kaputt ist?"],
    scene: "Illustrative Holzwerkstatt mit Attractap-Touch-Lesern, Steuerboxen, Tischkreissäge, Bandsäge und CNC-Fräse",
    static: "Ohne Bewegung", animated: "3D aktivieren", loading: "Werkstatt wird vorbereitet", live: "Interaktives Beispiel", still: "Illustriertes Beispiel", reset: "Zurück zum Ablauf", select: "Maschine erkunden",
    hardware: "Illustration, kein Schaltplan. Keine echte Maschine verbunden.", fallback: "Standbilder. Alle Schritte bleiben bedienbar.",
    machine: {
      "table-saw": { name: "Tischkreissäge", tag: "Nutzung & Übergabe", description: "Hier begleitet Attraccess Lea vom Identifizieren bis zum bestätigten Abschluss. Sie können den Leser, das Zubehör und den Arbeitsplatz im Ablauf ausprobieren." },
      bandsaw: { name: "Bandsäge", tag: "Meldung & Wartung", description: "Eine Beobachtung ist noch keine Nutzungssperre. Sehen Sie, wie eine Meldung in der Web-App bei Wartungsberechtigten ankommt und zur Wartung wird." },
      cnc: { name: "CNC-Fräse", tag: "Projekt & Betrieb", description: "Nutzung einem Projekt zuordnen, Dauer nachvollziehen und bei entsprechender Einrichtung abrechnen. Auch wiederkehrende Abläufe können als Flows konfiguriert werden." },
    },
    identify: { kicker: "01 / Ankommen", title: "Einweisen. Karte zuordnen. Im Alltag selbstständig loslegen.", text: "Lea kennt die Tischkreissäge und hat eine gültige Einweisung. Bei ihrem nächsten Besuch muss niemand wieder eine Liste durchsuchen: Sie hält ihre registrierte NFC-Karte an den Attractap Touch und startet dort ihre Nutzung.", point: "Für den normalen Touch-Ablauf muss sie nicht erst das Handy öffnen. Welche Einweisung oder Aufsicht nötig ist, legen Sie fest.", more: "Was vor dem ersten Arbeitstag eingerichtet wird", details: "Account und kompatible Karte zuordnen, Einweisung für Maschine oder Ressourcengruppe dokumentieren, Leser verbinden. Entzug, fällige Wiedereinweisung, Aufsicht, Wartung oder unzureichendes Guthaben können den Start weiterhin verhindern." },
    evaluate: { kicker: "02 / Vor dem Start", title: "Die kleine Frage, die sonst untergeht.", text: "Ist der Schiebestock da? Wurde das Zubehör geprüft? Sie wählen die Fragen, die für Ihre Ausstattung wichtig sind. Ein kurzer Check direkt am Leser macht sie zum Teil des Starts, nicht zum nächsten Schild an der Wand.", point: "Die Antwort wird zur Nutzung gespeichert. Attraccess zählt keine Teile und erkennt keinen Schaden: Die Person schaut nach und bestätigt.", more: "Ihre Fragen, Ihre Übergabepunkte", details: "Formulare lassen sich für Start, Übernahme und Ende konfigurieren, mit Text-, Zahlen-, Auswahl- und Ja-Bestätigungsfeldern. Eine fehlende oder beschädigte Sache sollte ehrlich dokumentiert werden können, statt eine falsche Alles-in-Ordnung-Bestätigung zu erzwingen." },
    apply: { kicker: "03 / Arbeiten", title: "Der Ablauf läuft mit. Nicht im Weg.", text: "Lea arbeitet an ihrem Projekt. Die Nutzung ist ihrer Person zugeordnet; Dauer und auf Wunsch das Projekt bleiben nachvollziehbar. Eine eingerichtete Maschinenanbindung überträgt die Freigabe an den vorgesehenen Schaltpunkt.", point: "Wiederkehrende Handgriffe, etwa einen Befehl an die Absaugung, können Sie als Flow an den Sitzungsstart knüpfen. Maschinenbedienung bleibt ein eigener Schritt.", more: "Projekte, Guthaben und Schnittstellen", details: "Nutzungen können Projekten zugeordnet werden. Mit eingerichtetem Abrechnungsmodul sind pauschale und/oder minutenbasierte Guthabentarife möglich; SumUp kann für Guthabenkäufe angebunden werden. HTTP, MQTT und Shelly sind mögliche Integrationen, kein verpflichtender Aufbau." },
    record: { kicker: "04 / Gut übergeben", title: "Nicht einfach gehen. Gut hinterlassen.", text: "Nach dem letzten Schnitt gehören Späne entfernt und Zubehör zurück an seinen Platz. Lea räumt selbst auf. Beim normalen Beenden erinnert die konfigurierte Abschlussfrage sie an die Übergabe und hält ihre Bestätigung fest.", point: "Für Sie bleibt sichtbar: Wer hat wann genutzt und was bestätigt? Das ersetzt keine Kontrolle vor Ort, gibt Ihnen aber einen nachvollziehbaren Ausgangspunkt statt bloßer Vermutungen.", more: "Was im Nutzungsverlauf steht", details: "Person, Beginn, Ende, Dauer, optional Projekt und Aufsicht sowie zugehörige Formularantworten. Die regulären Abschlussformulare gelten im normalen Beenden-Ablauf; automatische Beendigungen können sie umgehen. Ein Eintrag ist kein Beweis, wer einen Schaden verursacht hat." },
    connect: { kicker: "05 / Wenn etwas nicht stimmt", title: "Aus „ist kaputt“ wird ein Vorgang.", text: "An der Bandsäge fällt ein beschädigtes Sägeblatt auf. Das Mitglied meldet das Problem in der Web-App. Wartungsberechtigte sehen die Meldung und entscheiden, wann sie Wartung starten. Erst dann wird neue reguläre Nutzung gesperrt.", point: "Melden, entscheiden, reparieren, abschließen: Der Zustandswechsel in der Szene zeigt, warum diese Schritte nicht dasselbe sind.", more: "Wartung planbar machen", details: "Wartungspläne können an Nutzungsstunden, Nutzungsanzahl oder Zeitintervalle anknüpfen. Benachrichtigungen benötigen eingerichtete Empfänger und Kanäle. Problem-Anfragen sind im aktuellen Quellcode vorhanden; Verfügbarkeit, Wartungsmodul und Verhalten der installierten Version klären wir beim technischen Fit." },
    pilot: { kicker: "06 / Ihr Alltag, Ihre Regeln", title: ["Klein anfangen.", "Am echten Alltag messen."], text: "Nicht jede Maschine braucht die gleichen Fragen. Wir beginnen mit drei repräsentativen Ressourcen und richten gemeinsam einen Ablauf ein, der zu Ihren Menschen, Ihrer Hardware und Ihren Zuständigkeiten passt.", points: ["Drei Maschinen, 90 Tage", "Einweisungen, Checks und Verantwortliche festlegen", "Freigabe- und Fehlerverhalten vor Installation klären", "Gemeinsam mit Werkstattleitung, IT und Arbeitssicherheit auswerten"], note: "Konfiguration, Hardware und Funktionsumfang werden vorab geprüft." },
    cue: {
      overview: ["Ein ganz normaler Werkstatttag.", "Zubehör, Späne, Zuständigkeiten: Folgen Sie dem Ablauf und verändern Sie die Szene."],
      locked: ["Lea steht vor der Tischkreissäge.", "Tippen Sie auf den Leser oder auf den Karten-Button. Die Karte identifiziert, sie startet nicht die Säge."],
      identified: ["Lea ist identifiziert. Noch keine Nutzung gestartet.", "Der Leser zeigt die Ressource. „Ressource verwenden“ führt zum eingerichteten Start-Check."],
      supervision: ["Nicht jeder arbeitet schon allein.", "Echter Firmware-Render: Im separaten Beispiel wird eine berechtigte Aufsicht angefordert."],
      pending: ["Der Schiebestock liegt neben der Säge.", "Zubehör ansehen und die eingerichtete Frage beantworten. Keine automatische Teileerkennung."],
      checked: ["Lea hat das Zubehör geprüft.", "Die Frage ist bestätigt. Erst Absenden schließt diesen Start-Check ab."],
      submitted: ["Antwort erfasst, Nutzung gestartet.", "Die Maschine startet dadurch nicht von selbst. Ihre Bedienung bleibt ein eigener Schritt."],
      manual: ["Eine Nutzung, klar zugeordnet.", "Vergleichen Sie den Ablauf mit einem eingerichteten MQTT-Flow für die Absaugung."],
      automation: ["Der konfigurierte Signalweg wird sichtbar.", "Nutzungsstart → MQTT-Befehl. Dies zeigt die Einrichtung, keine bestätigte physische Schaltung."],
      dirty: ["Die Arbeit ist fertig. Der Arbeitsplatz noch nicht.", "Tippen Sie auf die Reste oder lassen Sie Lea unten aufräumen. Hier handelt ein Mensch, nicht die Software."],
      cleaned: ["Aufgeräumt. Noch nicht bestätigt.", "Die Späne sind weg, das Zubehör ist zurück. Lea beendet nun ihre Nutzung am Leser."],
      form: ["Eine kurze Frage zum Abschluss.", "Die Bestätigung bleibt leer, bis Lea sie selbst gibt. Aufräumen und Bestätigen sind zwei verschiedene Dinge."],
      "form-checked": ["Von Lea bestätigt. Noch nicht abgesendet.", "Der Haken erscheint auch am Leser. Mit Absenden wird die Antwort erfasst und die normale Nutzung beendet."],
      confirmed: ["Bereit für die nächste Person.", "Die Nutzung ist beendet. Leas Übergabebestätigung steht im zugehörigen Eintrag."],
      observed: ["Ein Schaden fällt auf.", "Die Bandsäge ist im Beispiel noch nicht auf Wartung gesetzt. Eine Meldung beginnt in der Web-App."],
      reported: ["Gemeldet ist noch nicht gesperrt.", "Die Anfrage wartet auf die Entscheidung einer wartungsberechtigten Person."],
      active: ["Wartung aktiv. Kein neuer regulärer Start.", "Wartungspersonal kann weiter für Service zugreifen. Dies ist keine Notabschaltung."],
      resolved: ["Reparatur erledigt, Wartung abgeschlossen.", "Nach der tatsächlichen Arbeit gibt die berechtigte Person die Ressource wieder für reguläre Nutzung frei."],
      pilot: ["So wenig Reibung wie möglich. So viel Ablauf wie nötig.", "Welche drei Ressourcen stehen stellvertretend für Ihren Alltag?"],
    },
    features: { title: "Mehr als die drei Maschinen im Beispiel.", text: "Ein gemeinsam genutzter Arbeitsbereich besteht nicht nur aus Sägen. Dieselben Bausteine verbinden Ausstattung, Menschen und Betrieb.", source: "Funktionen in der Dokumentation nachlesen", cards: [
      ["Einweisungen & Aufsicht", "Einweisungen vergeben oder entziehen, Ressourcengruppen nutzen und beaufsichtigte Nutzung nach Ihren Regeln ermöglichen.", "resources/introductions"],
      ["Eigene Checklisten", "Fragen bei Start, Übernahme und Ende. Antworten bleiben der Nutzung zugeordnet.", "forms/overview"],
      ["Nutzungsverlauf & Projekte", "Person, Zeit, Projekt und Aufsicht nachvollziehen; Formularantworten und Nutzungsdaten auswerten.", "resources/usage-tracking"],
      ["Wartung & Zuständigkeiten", "Arbeiten dokumentieren, Wartungspläne nach Zeit oder Nutzung einrichten und berechtigte Personen zuordnen.", "resources/maintenance"],
      ["Türen & Ressourcengruppen", "Auch Türen als Ressourcen verwalten. Gruppen bündeln Einweisungen für mehrere Maschinen; physische Türsteuerung wird separat angebunden.", "resources/overview"],
      ["Guthaben & Abrechnung", "Mit eingerichtetem Modul pauschal und/oder pro Minute abrechnen, Transaktionen nachvollziehen und optional SumUp anbinden.", "billing/overview"],
      ["Automatisierte Abläufe", "Konfigurierte Ereignisse mit HTTP-, MQTT- und anderen Flow-Aktionen verbinden, passend zu Ihrer Installation.", "flows/overview"],
      ["Ihre Infrastruktur", "Self-hosted, quelloffen einsehbar. Bestehende Identitäten über eingerichtetes SSO mit SAML/OIDC nutzen. Passkeys stehen als weitere Anmeldemöglichkeit zur Verfügung.", "installation/docker-compose"],
    ], caveat: "Nicht alles ist standardmäßig aktiviert: Version, Module, Konfiguration und passende Hardware bestimmen den konkreten Umfang." },
    audiences: { title: "Andere Räume. Ähnliche Herausforderungen.", cases: [
      ["Makerspaces & Fab Labs", "Viele Mitglieder, unterschiedliche Erfahrung und Ausstattung, die alle gemeinsam nutzen. Klare Übergaben statt separater Listen."],
      ["Hochschulen & Forschung", "Wechselnde Kurse und Projekte. Einweisungen, Rollen und Aufsicht bleiben nachvollziehbar."],
      ["Industrie & Ausbildung", "Maschinenpools und Trainingsflächen mit klaren Verantwortlichkeiten und dokumentierter Nutzung."],
    ] },
    newsletter: { title: "Neuigkeiten aus dem Betrieb.", text: "Gelegentliche Updates zu Verfügbarkeit, Weiterentwicklung und dem Betrieb gemeinsam genutzter Ressourcen. Kein Blog-Abo.", email: "E-Mail-Adresse", name: "Name (optional)", consent: "Ich willige ein, dass meine Angaben für den Newsletter verarbeitet werden.", submit: "Auf dem Laufenden bleiben", note: "Bestätigung per E-Mail. Abmeldung jederzeit möglich." },
  },
  en: {
    chapter: "Workshop day chapter", tour: "A day in your workshop", nav: ["Everyday life", "Arrive", "Check", "Use", "Hand over", "Maintain", "Your start"],
    hero: ["More workshop.", "Less chasing up."],
    intro: "Sawdust on the saw. Accessories out of place. And who's dealing with the broken machine? Shared equipment needs more than a key.",
    promise: "Attraccess connects briefings, short checks, usage and maintenance. So looking after your equipment becomes part of the routine, rather than another reminder.",
    explore: "Try a workshop day", skip: "Skip to the pilot", meet: "Your workshop, in miniature", duration: "From arriving to handing over.",
    pain: ["Who may use the saw?", "Where are the accessories?", "Who clears the sawdust?", "What if something breaks?"],
    scene: "Illustrative woodworking workshop with Attractap Touch readers, control boxes, a table saw, bandsaw and CNC router",
    static: "Without motion", animated: "Enable 3D", loading: "Preparing the workshop", live: "Interactive example", still: "Illustrated example", reset: "Back to the story", select: "Explore a machine",
    hardware: "Illustration, not a wiring plan. No real equipment connected.", fallback: "Still images. Every step remains usable.",
    machine: {
      "table-saw": { name: "Table saw", tag: "Use & handover", description: "Follow Lea from identification to a confirmed handoff. Try the reader, accessory check and cleanup steps in the story." },
      bandsaw: { name: "Bandsaw", tag: "Reports & maintenance", description: "An observation is not an access restriction. Follow a web-app report to an authorized maintainer's decision." },
      cnc: { name: "CNC router", tag: "Projects & operations", description: "Link usage to a project, review duration and charge for use when configured. Set up flows for recurring operational steps." },
    },
    identify: { kicker: "01 / Arrive", title: "Brief once. Link a card. Make coming back easy.", text: "Lea knows the table saw and has a current briefing. On her next visit, nobody has to search another list: she presents her registered NFC card to the Attractap Touch and starts her usage there.", point: "For the ordinary Touch workflow, she doesn't need to open her phone first. You decide which briefings or supervision are required.", more: "What gets set up before the first working day", details: "Link an account and compatible card, record a machine or resource-group briefing, and connect the reader. Revocation, due retraining, supervision, maintenance or insufficient credit can still prevent a start." },
    evaluate: { kicker: "02 / Before starting", title: "The small question that otherwise gets missed.", text: "Is the push stick there? Have the accessories been checked? You choose the questions that matter for your equipment. A short check at the reader makes them part of starting, not another sign on the wall.", point: "The answer is saved with the session. Attraccess doesn't count parts or detect damage: the person checks and confirms.", more: "Your questions, your handoff points", details: "Configure forms for start, takeover and end, using text, number, selection and affirmative-confirmation fields. Allow people to honestly record a missing or damaged item rather than forcing an untrue all-clear." },
    apply: { kicker: "03 / Get to work", title: "Alongside the work. Not in its way.", text: "Lea gets on with her project. The session is linked to her identity; duration and, optionally, the project stay traceable. A configured machine integration applies the release at the intended control point.", point: "Recurring steps, such as sending a command to extraction, can be attached to session start through a configured flow. Operating the machine remains a separate step.", more: "Projects, credit and interfaces", details: "Sessions can be linked to projects. An enabled billing module supports flat and/or per-minute credit pricing; SumUp can be configured for credit purchases. HTTP, MQTT and Shelly are integration options, not a mandatory stack." },
    record: { kicker: "04 / Hand over well", title: "Don't just leave. Leave it ready.", text: "After the last cut, sawdust needs removing and accessories belong back in place. Lea does the cleanup herself. When she ends normal usage, the configured closing question reminds her about the handoff and records her confirmation.", point: "You can see who used the machine, when, and what they confirmed. It doesn't replace checking in person, but gives you a traceable starting point instead of guesswork.", more: "What the usage history records", details: "Person, start, end, duration, optional project and supervision, plus associated form answers. End forms apply to the ordinary ending flow; automatic endings can bypass them. A record is not proof of who caused damage." },
    connect: { kicker: "05 / When something's wrong", title: "Turn “it's broken” into a process.", text: "Someone notices a damaged blade on the bandsaw. The member reports it in the web app. Authorized maintainers review the request and decide when to start maintenance. Only then is ordinary new use blocked.", point: "Report, decide, repair, complete: the scene's changing state shows why those are different steps.", more: "Make maintenance planned work", details: "Maintenance schedules can use usage hours, session counts or elapsed time. Notifications need configured recipients and channels. Problem requests exist in current source; we check availability, maintenance entitlement and installed-version behavior during technical fit." },
    pilot: { kicker: "06 / Your routine, your rules", title: ["Start small.", "Measure it against real work."], text: "Not every machine needs the same questions. Start with three representative resources and build a workflow around your people, hardware and responsibilities.", points: ["Three machines, 90 days", "Agree briefings, checks and responsible people", "Define release and failure behavior before installation", "Review with workshop management, IT and safety stakeholders"], note: "Configuration, hardware and applicable features are assessed first." },
    cue: {
      overview: ["Just another day in the workshop.", "Accessories, sawdust, responsibilities: follow the story and change the scene."],
      locked: ["Lea is at the table saw.", "Tap the reader or the card button. The card identifies her; it doesn't start the saw."],
      identified: ["Lea is identified. Usage hasn't started.", "The reader shows the resource. “Ressource verwenden” leads to the configured start check."],
      supervision: ["Not everyone works alone yet.", "Actual firmware render: a separate example asks for an eligible supervisor."],
      pending: ["The push stick is beside the saw.", "Inspect the accessory and answer the configured question. No automatic parts detection."],
      checked: ["Lea has checked the accessories.", "The question is confirmed. Submitting completes this start check."],
      submitted: ["Answer recorded. Session started.", "The machine doesn't start itself. Its physical controls remain a separate step."],
      manual: ["One session, linked to a person.", "Compare this with a configured MQTT flow for extraction."],
      automation: ["The configured signal path becomes visible.", "Usage start → MQTT command. This shows configuration, not confirmed physical actuation."],
      dirty: ["The work is finished. The cleanup isn't.", "Tap the scraps or let Lea clean up below. A person acts here, not the software."],
      cleaned: ["Cleaned up. Not yet confirmed.", "The sawdust is gone and the accessory is back. Lea now ends her usage at the reader."],
      form: ["One short closing question.", "The confirmation stays unchecked until Lea answers. Cleanup and confirmation are separate steps."],
      "form-checked": ["Confirmed by Lea. Not yet submitted.", "The reader shows her answer too. Submitting records the answer and ends ordinary usage."],
      confirmed: ["Ready for the next person.", "The session has ended. Lea's handoff confirmation is attached to its record."],
      observed: ["Someone notices damage.", "The bandsaw hasn't been put under maintenance in this example. Reporting starts in the web app."],
      reported: ["Reported doesn't mean blocked.", "The request awaits an authorized maintainer's decision."],
      active: ["Maintenance active. No ordinary new start.", "Maintenance personnel can still access it for service. This is not an emergency stop."],
      resolved: ["Repair done. Maintenance completed.", "After the physical work, an authorized person restores ordinary availability."],
      pilot: ["As little friction as possible. As much process as needed.", "Which three resources represent your daily work?"],
    },
    features: { title: "Beyond the three machines in this example.", text: "Shared spaces aren't only about saws. The same building blocks connect equipment, people and operations.", source: "Read the documented features", cards: [
      ["Briefings & supervision", "Grant or revoke introductions, use resource groups and enable supervised usage according to your rules.", "resources/introductions"],
      ["Your own checklists", "Questions at start, takeover and end. Answers stay associated with the session.", "forms/overview"],
      ["Usage history & projects", "Trace people, time, projects and supervision; review form responses and usage records.", "resources/usage-tracking"],
      ["Maintenance & responsibilities", "Document work, schedule by time or usage and assign eligible personnel.", "resources/maintenance"],
      ["Doors & resource groups", "Manage doors as resources too. Groups share introductions across machines; physical door control requires its own integration.", "resources/overview"],
      ["Credit & billing", "With the enabled module, configure flat and/or per-minute charges, review transactions and optionally connect SumUp.", "billing/overview"],
      ["Operational automation", "Connect configured events to HTTP, MQTT and other flow actions for your installation.", "flows/overview"],
      ["Your infrastructure", "Self-hosted and source-available. Use existing identities with configured SAML/OIDC SSO. Passkeys offer another way to sign in.", "installation/docker-compose"],
    ], caveat: "Not everything is enabled by default: version, modules, configuration and suitable hardware determine the available features." },
    audiences: { title: "Different spaces. Familiar challenges.", cases: [
      ["Makerspaces & fab labs", "Many members, different experience and shared equipment. Clear handoffs instead of separate lists."],
      ["Universities & research", "Changing courses and projects. Briefings, roles and supervision remain traceable."],
      ["Industry & training", "Machine pools and training areas with clear responsibilities and documented usage."],
    ] },
    newsletter: { title: "Notes from the real world.", text: "Occasional updates on availability, product development and operating shared resources. Not a blog subscription.", email: "Email address", name: "Name (optional)", consent: "I consent to my details being processed for the newsletter.", submit: "Keep me updated", note: "Confirmation by email. Unsubscribe at any time." },
  },
} as const;
