import type { ChapterId, MachineId } from "./types";

export const chapters: { view: ChapterId; anchor: string }[] = [
  { view: "overview", anchor: "system" }, { view: "identify", anchor: "loop" },
  { view: "evaluate", anchor: "permissions" }, { view: "apply", anchor: "release" },
  { view: "record", anchor: "sessions" }, { view: "connect", anchor: "operations" },
  { view: "pilot", anchor: "pilot" },
];
export const machines: MachineId[] = ["table-saw", "bandsaw", "cnc"];

export const workshopCopy = {
  de: {
    chapter: "Station im Werkstattalltag", tour: "Ein Tag in Ihrer Werkstatt", nav: ["Alltag", "Ankommen", "Prüfen", "Nutzen", "Übergeben", "Wartung", "Ihr Start"],
    hero: ["Mehr Werkstatt.", "Weniger Hinterherlaufen."],
    intro: "Späne auf der Säge. Zubehör nicht am Platz. Und wer kümmert sich um die defekte Maschine? Gemeinsam genutzte Ausstattung braucht mehr als einen Schlüssel.",
    promise: "Attraccess verbindet Einweisungen, kurze Checks, Nutzung und Wartung. Damit der gute Umgang mit Ihrer Ausstattung Teil des Alltags wird, statt ständig eine Erinnerung zu brauchen.",
    explore: "Einen Werkstatttag ausprobieren", skip: "Direkt zum Pilotprojekt", meet: "Ihre Werkstatt, im Kleinen", duration: "Vom Ankommen bis zur nächsten Person.",
    pain: ["Wer darf an die Säge?", "Wo ist das Zubehör?", "Wer räumt die Späne weg?", "Und wenn etwas kaputt ist?"],
    scene: "Illustrative Holzwerkstatt mit Attractap-Touch-Lesern, Steuerboxen, Tischkreissäge, Bandsäge und CNC-Fräse",
    static: "Ohne Bewegung", animated: "3D aktivieren", loading: "Werkstatt wird vorbereitet", live: "Interaktives Beispiel", still: "Illustriertes Beispiel", reset: "Zurück zum Ablauf", select: "Maschine erkunden",
    hardware: "Eine Beispielwerkstatt zum Ausprobieren. Es werden keine echten Maschinen gesteuert.", fallback: "Die Werkstatt wird als Standbild gezeigt. Den Ablauf können Sie weiterhin ausprobieren.",
    machine: {
      "table-saw": { name: "Tischkreissäge", tag: "Nutzung & Übergabe", description: "Begleiten Sie Lea vom Vorhalten der Karte bis zur bestätigten Übergabe. Probieren Sie aus, wie sie den Leser nutzt, das Zubehör prüft und den Arbeitsplatz aufräumt." },
      bandsaw: { name: "Bandsäge", tag: "Meldung & Wartung", description: "Ein Problem braucht jemanden, der sich kümmert. Folgen Sie einer Meldung in der Web-App bis zur Entscheidung der zuständigen Wartungsperson." },
      cnc: { name: "CNC-Fräse", tag: "Projekt & Betrieb", description: "Welches Projekt hat die Maschine wie lange genutzt? Behalten Sie den Überblick und rechnen Sie die Nutzung auf Wunsch ab. Abrechnung und automatisierte Abläufe werden passend zu Ihrer Werkstatt eingerichtet." },
    },
    identify: { kicker: "01 / Ankommen", title: "Einweisen. Karte zuordnen. Im Alltag selbstständig loslegen.", text: "Lea kennt die Tischkreissäge und hat eine gültige Einweisung. Bei ihrem nächsten Besuch muss niemand wieder eine Liste durchsuchen: Sie hält ihre registrierte NFC-Karte an den Attractap Touch und startet dort ihre Nutzung.", point: "Lea erledigt diese Schritte direkt am Leser, ohne ihr Handy zu brauchen. Welche Einweisung oder Aufsicht nötig ist, legen Sie fest.", more: "Vor dem ersten Werkstatttag", details: "Jede Person erhält ein Benutzerkonto mit einer kompatiblen Karte. Sie dokumentieren die Einweisung für einzelne Maschinen oder eine Maschinengruppe und verbinden den Leser. Vor dem Start müssen die Voraussetzungen erfüllt sein: etwa eine aktuelle Einweisung, nötige Aufsicht, eine verfügbare Maschine und bei kostenpflichtiger Nutzung ausreichend Guthaben. Zugangsrechte können Sie auch wieder entziehen." },
    evaluate: { kicker: "02 / Vor dem Start", title: "Die kleine Frage, die sonst untergeht.", text: "Ist der Schiebestock da? Wurde das Zubehör geprüft? Sie wählen die Fragen, die für Ihre Ausstattung wichtig sind. Ein kurzer Check direkt am Leser macht sie zum Teil des Starts, nicht zum nächsten Schild an der Wand.", point: "Die Antwort wird zur Nutzung gespeichert. Attraccess zählt keine Teile und erkennt keinen Schaden: Die Person schaut nach und bestätigt.", more: "Ihre Fragen, Ihre Übergabepunkte", details: "Legen Sie fest, was beim Start, bei einer Übernahme und zum Abschluss gefragt wird. Antworten können als Text, Zahl, Auswahl oder Bestätigung erfasst werden. Für fehlendes oder beschädigtes Zubehör bieten sich eine Zustandsauswahl und ein Hinweisfeld an, damit auch Probleme festgehalten werden können." },
    apply: { kicker: "03 / Arbeiten", title: "Begleitet die Arbeit. Hält sie nicht auf.", text: "Lea arbeitet an ihrem Projekt. Attraccess hält fest, wer die Maschine wie lange nutzt und auf Wunsch für welches Projekt. So bleibt die Nutzung nachvollziehbar, ohne sie später aus einzelnen Listen zusammenzusuchen.", point: "Mit passender Anbindung lässt sich etwa die Absaugung beim Nutzungsstart automatisch ansteuern. Die Maschine selbst bedient Lea weiterhin separat.", more: "Nutzung zuordnen und abrechnen", details: "Ordnen Sie Nutzungen einem Projekt zu. Mit eingerichteter Abrechnung können Sie eine Pauschale pro Nutzung, einen Minutenpreis oder beides vom Guthaben abziehen. Auf Wunsch lässt sich Guthaben über SumUp aufladen. Welche Geräte angebunden und Abläufe automatisiert werden können, prüfen wir vorab mit Ihnen." },
    record: { kicker: "04 / Gut übergeben", title: "Nicht einfach gehen. Gut hinterlassen.", text: "Nach dem letzten Schnitt gehören Späne entfernt und Zubehör zurück an seinen Platz. Lea räumt selbst auf. Wenn sie ihre Nutzung am Leser beendet, erinnert die von Ihnen festgelegte Abschlussfrage an die Übergabe und hält ihre Bestätigung fest.", point: "Für Sie bleibt sichtbar: Wer hat wann genutzt und was bestätigt? Das ersetzt keine Kontrolle vor Ort, gibt Ihnen aber einen nachvollziehbaren Ausgangspunkt statt bloßer Vermutungen.", more: "Was im Nutzungsverlauf steht", details: "Sie sehen Person, Beginn, Ende und Dauer sowie die Antworten auf Ihre Fragen. Wenn angegeben, werden auch Projekt und Aufsicht festgehalten. Wird eine Nutzung automatisch beendet, kann die Abschlussbestätigung fehlen. Der Verlauf hilft bei Rückfragen, beweist aber nicht, wer einen Schaden verursacht hat." },
    connect: { kicker: "05 / Wenn etwas nicht stimmt", title: "Ein Problem melden. Die Wartung angehen.", text: "An der Bandsäge fällt ein beschädigtes Sägeblatt auf. Im Beispiel meldet das Mitglied das Problem in der Web-App. Die zuständige Wartungsperson prüft die Meldung und startet die Wartung. Erst dann können Mitglieder keine neue Nutzung beginnen; laufende Nutzungen werden dadurch nicht beendet.", point: "Die Meldung hält fest, was aufgefallen ist. Die zuständige Person entscheidet über die Wartung und dokumentiert den Abschluss nach der Reparatur.", more: "Wartung planbar machen", details: "Planen Sie Wartungen nach Nutzungsstunden, Anzahl der Nutzungen oder festen Zeitabständen. Sie legen fest, wer über welche Wege benachrichtigt wird. Vor dem Einsatz prüfen wir, ob die gezeigte Problemmeldung und die gewünschten Wartungsfunktionen mit Ihrer Softwareversion und den gebuchten Modulen verfügbar sind." },
    pilot: { kicker: "06 / Ihr Alltag, Ihre Regeln", title: ["Klein anfangen.", "Am echten Alltag messen."], text: "Nicht jede Maschine braucht die gleichen Fragen. Wir wählen mit Ihnen drei typische Maschinen aus und planen einen Ablauf, der zu Ihrem Team, Ihrer Ausstattung und Ihren Zuständigkeiten passt.", points: ["Drei Maschinen im Werkstattalltag erproben", "Einweisungen, Checks und Verantwortliche festlegen", "Vorab klären, wann Nutzung möglich ist und was bei Störungen passiert", "Gemeinsam mit Werkstattleitung, IT und Arbeitssicherheit auswerten"], note: "Umfang, Dauer und technische Voraussetzungen stimmen wir vorab mit Ihnen ab." },
    cue: {
      overview: ["Ein ganz normaler Werkstatttag.", "Zubehör, Späne, Zuständigkeiten: Folgen Sie dem Ablauf und verändern Sie die Szene."],
      locked: ["Lea steht vor der Tischkreissäge.", "Tippen Sie auf den Leser oder auf den Karten-Button. Die Karte identifiziert, sie startet nicht die Säge."],
      identified: ["Der Leser hat Lea erkannt. Ihre Nutzung ist noch nicht gestartet.", "Mit „Ressource verwenden“ am Leser beginnt die Prüfung vor dem Start."],
      supervision: ["Nicht jeder arbeitet schon allein.", "Das zusätzliche Beispiel zeigt, wie eine berechtigte Aufsichtsperson die Nutzung bestätigt."],
      pending: ["Der Schiebestock liegt neben der Säge.", "Zubehör ansehen und die eingerichtete Frage beantworten. Keine automatische Teileerkennung."],
      checked: ["Lea hat das Zubehör geprüft.", "Die Frage ist bestätigt. Erst Absenden schließt diesen Start-Check ab."],
      submitted: ["Antwort erfasst, Nutzung gestartet.", "Die Maschine startet dadurch nicht von selbst. Ihre Bedienung bleibt ein eigener Schritt."],
      manual: ["Eine Nutzung, klar zugeordnet.", "Probieren Sie aus, wie sich die Absaugung mit passender Einrichtung beim Nutzungsstart ansteuern lässt."],
      automation: ["Ein Handgriff lässt sich automatisieren.", "Beim Nutzungsstart wird ein Befehl an die Absaugung gesendet. Das Beispiel steuert keine echte Anlage."],
      dirty: ["Die Arbeit ist fertig. Der Arbeitsplatz noch nicht.", "Tippen Sie auf die Reste oder lassen Sie Lea unten aufräumen. Hier handelt ein Mensch, nicht die Software."],
      cleaned: ["Aufgeräumt. Noch nicht bestätigt.", "Die Späne sind weg, das Zubehör ist zurück. Lea beendet nun ihre Nutzung am Leser."],
      form: ["Eine kurze Frage zum Abschluss.", "Die Bestätigung bleibt leer, bis Lea sie selbst gibt. Aufräumen und Bestätigen sind zwei verschiedene Dinge."],
      "form-checked": ["Von Lea bestätigt. Noch nicht abgesendet.", "Mit Absenden wird Leas Antwort gespeichert und ihre Nutzung beendet."],
      confirmed: ["Bereit für die nächste Person.", "Die Nutzung ist beendet. Leas Übergabebestätigung steht im zugehörigen Eintrag."],
      observed: ["Ein Schaden fällt auf.", "Die Bandsäge ist im Beispiel noch nicht auf Wartung gesetzt. Eine Meldung beginnt in der Web-App."],
      reported: ["Gemeldet ist noch nicht gesperrt.", "Die Anfrage wartet auf die Entscheidung einer wartungsberechtigten Person."],
      active: ["In Wartung. Keine neue Nutzung für Mitglieder.", "Wartungspersonal kann für die Reparatur weiter zugreifen. Laufende Maschinen werden nicht automatisch gestoppt."],
      resolved: ["Reparatur erledigt, Wartung abgeschlossen.", "Nach der Reparatur gibt die zuständige Wartungsperson die Maschine wieder für Mitglieder frei."],
      pilot: ["So wenig Aufwand wie möglich. So viel Begleitung wie nötig.", "Welche drei Maschinen stehen stellvertretend für Ihren Alltag?"],
    },
    features: { title: "Mehr als die drei Maschinen im Beispiel.", text: "Ein gemeinsam genutzter Arbeitsbereich besteht nicht nur aus Sägen. Dieselben Bausteine verbinden Ausstattung, Menschen und Betrieb.", cards: [
      ["Einweisungen & Aufsicht", "Einweisungen dokumentieren, Zugangsrechte erteilen oder entziehen und festlegen, wer nur unter Aufsicht arbeiten darf."],
      ["Eigene Checklisten", "Fragen bei Start, Übernahme und Ende. Antworten bleiben der Nutzung zugeordnet."],
      ["Nutzungsverlauf & Projekte", "Person, Zeit, Projekt und Aufsicht nachvollziehen; Formularantworten und Nutzungsdaten auswerten."],
      ["Wartung & Zuständigkeiten", "Arbeiten dokumentieren, Wartungspläne nach Zeit oder Nutzung einrichten und berechtigte Personen zuordnen."],
      ["Türen & Maschinengruppen", "Auch den Zugang durch Türen verwalten und Einweisungen für mehrere Maschinen bündeln. Die Türsteuerung benötigt eine passende Anbindung."],
      ["Guthaben & Abrechnung", "Mit eingerichteter Abrechnung pauschal oder pro Minute abrechnen und Zahlungen nachvollziehen. Guthaben lässt sich auf Wunsch über SumUp aufladen."],
      ["Automatisierte Abläufe", "Wiederkehrende Schritte mit dem Nutzungsstart oder -ende verbinden, etwa die Ansteuerung der Absaugung. Passende Geräte und Abläufe werden dafür eigens eingerichtet."],
      ["Betrieb auf Ihren Servern", "Betreiben Sie Attraccess auf Ihren eigenen Servern. Auf Wunsch wird die Anmeldung mit bestehenden Organisationskonten eingerichtet. Alternativ ist auch eine Anmeldung per Passkey möglich."],
    ], caveat: "Welche Funktionen Sie nutzen können, hängt von Ihrer Softwareversion, den gebuchten Modulen und der Einrichtung ab. Für die Steuerung von Geräten ist passende Hardware nötig." },
    audiences: { title: "Andere Räume. Ähnliche Herausforderungen.", cases: [
      ["Makerspaces & Fab Labs", "Viele Mitglieder, unterschiedliche Erfahrung und Ausstattung, die alle gemeinsam nutzen. Klare Übergaben statt separater Listen."],
      ["Hochschulen & Forschung", "Wechselnde Kurse und Projekte. Einweisungen, Rollen und Aufsicht bleiben nachvollziehbar."],
      ["Industrie & Ausbildung", "Maschinenpools und Trainingsflächen mit klaren Verantwortlichkeiten und dokumentierter Nutzung."],
    ] },
    newsletter: { title: "Neuigkeiten für Ihre Werkstatt.", text: "Gelegentliche Neuigkeiten zu Attraccess und zur Organisation gemeinsam genutzter Werkstätten.", email: "E-Mail-Adresse", name: "Name (optional)", consent: "Ich willige ein, dass meine Angaben für den Newsletter verarbeitet werden.", submit: "Auf dem Laufenden bleiben", note: "Bestätigung per E-Mail. Abmeldung jederzeit möglich." },
  },
  en: {
    chapter: "Steps in a workshop day", tour: "A day in your workshop", nav: ["Overview", "Arrive", "Check", "Work", "Hand over", "Maintain", "Get started"],
    hero: ["More time making.", "Less time chasing."],
    intro: "Sawdust on the saw. Accessories out of place. And who's dealing with the broken machine? Shared equipment needs more than a key.",
    promise: "Attraccess brings safety briefings, quick checks, equipment use and maintenance together. So looking after shared equipment becomes part of the routine, rather than another reminder.",
    explore: "Try a workshop day", skip: "Skip to the pilot", meet: "Your workshop, in miniature", duration: "From arriving to handing over.",
    pain: ["Who may use the saw?", "Where are the accessories?", "Who clears the sawdust?", "What if something breaks?"],
    scene: "Illustrative woodworking workshop with Attractap Touch readers, control boxes, a table saw, bandsaw and CNC router",
    static: "Pause animation", animated: "Enable 3D", loading: "Preparing the workshop", live: "Interactive example", still: "Illustrated example", reset: "Back to the story", select: "Explore a machine",
    hardware: "A sample workshop to explore. No real machines are being controlled.", fallback: "The workshop is shown as a still image. You can still try every step.",
    machine: {
      "table-saw": { name: "Table saw", tag: "Use & handover", description: "Follow Lea from presenting her card to confirming the handover. Try the reader, accessory check and cleanup steps in the story." },
      bandsaw: { name: "Bandsaw", tag: "Reports & maintenance", description: "A problem needs someone to take care of it. Follow a report in the web app through to the maintenance team's decision." },
      cnc: { name: "CNC router", tag: "Projects & operations", description: "Which project used the machine, and for how long? Keep track and charge for use if needed. Billing and automated routines are set up to suit your workshop." },
    },
    identify: { kicker: "01 / Arrive", title: "Give a briefing. Link a card. Make coming back easy.", text: "Lea knows the table saw and her safety briefing is up to date. On her next visit, nobody has to search another list: she presents her registered NFC card to the Attractap Touch and starts her session there.", point: "Lea completes these steps at the reader, without needing her phone. You decide which briefings or supervision are required.", more: "Before the first workshop day", details: "Each person gets an account linked to a compatible card. You record their briefing for a machine or group of machines and connect the reader. Before starting, they must meet the requirements: an up-to-date briefing, any required supervision, an available machine and enough credit for paid use. You can also withdraw access when needed." },
    evaluate: { kicker: "02 / Before starting", title: "The small question that otherwise gets missed.", text: "Is the push stick there? Have the accessories been checked? You choose the questions that matter for your equipment. A short check at the reader makes them part of starting, not another sign on the wall.", point: "The answer is saved with the session. Attraccess doesn't count parts or detect damage: the person checks and confirms.", more: "Your questions, your handover points", details: "Choose what to ask at the start, when someone takes over and at the end. People can enter text or numbers, choose an answer or confirm a check. A choice of conditions and a notes field let them record missing or damaged accessories too." },
    apply: { kicker: "03 / Get to work", title: "Alongside the work. Not in its way.", text: "Lea gets on with her project. Attraccess records who uses the machine, for how long and, if selected, for which project. You can follow its use without piecing together separate lists afterwards.", point: "With a suitable connection, the start of a session can send a command to the dust extraction system automatically. Lea still operates the machine separately.", more: "Track use and manage charges", details: "Link sessions to projects. With billing set up, you can deduct a flat fee per session, a per-minute charge or both from a user's credit balance. Optional SumUp payments let people top up their credit. Together, we check which devices can be connected and which routines can be automated before installation." },
    record: { kicker: "04 / Hand over well", title: "Don't just leave. Leave it ready.", text: "After the last cut, sawdust needs removing and accessories belong back in place. Lea does the cleanup herself. When she ends her session at the reader, the closing question you chose reminds her about the handover and records her confirmation.", point: "You can see who used the machine, when, and what they confirmed. It doesn't replace checking in person, but gives you a clear starting point instead of guesswork.", more: "What the usage history records", details: "See the person, start, end, duration and answers to your questions, along with the project and supervisor where provided. If a session ends automatically, the closing confirmation may be missing. The history helps with follow-up questions, but isn't proof of who caused damage." },
    connect: { kicker: "05 / When something's wrong", title: "Report a problem. Get maintenance under way.", text: "Someone notices a damaged blade on the bandsaw. In this example, the member reports it in the web app. An authorized member of the maintenance team reviews the report and starts maintenance. Only then are members prevented from starting new sessions; existing sessions are not ended.", point: "The report records what someone noticed. The person responsible decides on maintenance and records its completion after the repair.", more: "Plan ahead for maintenance", details: "Schedule maintenance by hours of use, number of sessions or fixed intervals. You choose who receives notifications and how. Before installation, we check that the problem-reporting example and the maintenance features you need are available with your software version and selected modules." },
    pilot: { kicker: "06 / Your routine, your rules", title: ["Start small.", "Measure it against real work."], text: "Not every machine needs the same questions. Together, we choose three typical machines and plan a routine around your team, equipment and responsibilities.", points: ["Try three machines in everyday workshop use", "Agree briefings, checks and who is responsible", "Agree when use is allowed and what happens if something goes wrong", "Review with workshop management, IT and safety teams"], note: "We agree the scope, duration and technical requirements with you in advance." },
    cue: {
      overview: ["Just another day in the workshop.", "Accessories, sawdust, responsibilities: follow the story and change the scene."],
      locked: ["Lea is at the table saw.", "Tap the reader or the card button. The card identifies her; it doesn't start the saw."],
      identified: ["The reader recognizes Lea. Her session hasn't started.", "Choose “Ressource verwenden” (use the machine) on the reader to begin the check."],
      supervision: ["Not everyone works alone yet.", "This additional example shows how an authorized supervisor confirms someone's use of the machine."],
      pending: ["The push stick is beside the saw.", "Inspect the accessory and answer the configured question. No automatic parts detection."],
      checked: ["Lea has checked the accessories.", "The question is confirmed. Submitting completes this start check."],
      submitted: ["Answer recorded. Session started.", "The machine doesn't start itself. Its physical controls remain a separate step."],
      manual: ["One session, linked to a person.", "Try adding a command to the dust extraction system when the session starts. This needs to be set up for your equipment."],
      automation: ["One less step to do by hand.", "Starting the session sends a command to the dust extraction system. This example doesn't control real equipment."],
      dirty: ["The work is finished. The cleanup isn't.", "Tap the scraps or let Lea clean up below. A person acts here, not the software."],
      cleaned: ["Cleaned up. Not yet confirmed.", "The sawdust is gone and the accessory is back. Lea now ends her session at the reader."],
      form: ["One short closing question.", "The confirmation stays unchecked until Lea answers. Cleanup and confirmation are separate steps."],
      "form-checked": ["Confirmed by Lea. Not yet submitted.", "Submitting saves Lea's answer and ends her session."],
      confirmed: ["Ready for the next person.", "The session has ended. Lea's handover confirmation is saved with it."],
      observed: ["Someone notices damage.", "The bandsaw hasn't been put under maintenance in this example. Reporting starts in the web app."],
      reported: ["Reported doesn't mean blocked.", "The request awaits an authorized maintainer's decision."],
      active: ["Under maintenance. No new sessions for members.", "The maintenance team can still access it for repairs. Running machines are not automatically stopped."],
      resolved: ["Repair done. Maintenance completed.", "After the repair, an authorized person makes the machine available to members again."],
      pilot: ["As little effort as possible. As much guidance as needed.", "Which three machines represent your daily work?"],
    },
    features: { title: "Beyond the three machines in this example.", text: "Shared spaces aren't only about saws. Bring access, equipment use and maintenance together across your workshop.", cards: [
      ["Safety briefings & supervision", "Record briefings, grant or withdraw access and decide who needs supervision to use a machine."],
      ["Your own checklists", "Questions at start, takeover and end. Answers stay associated with the session."],
      ["Usage history & projects", "Trace people, time, projects and supervision; review form responses and usage records."],
      ["Maintenance & responsibilities", "Record maintenance work, schedule it by time or use and assign the people responsible."],
      ["Doors & machine groups", "Manage door access and cover groups of machines with a shared briefing. Door control needs a suitable connection to your hardware."],
      ["Credit & billing", "With billing set up, charge per session or per minute and keep track of payments. Offer credit top-ups through SumUp if needed."],
      ["Automated routines", "Link recurring steps to the start or end of a session, such as sending a command to dust extraction. Suitable equipment and routines need to be set up first."],
      ["Run it on your servers", "Host Attraccess on your own servers. Sign-in with existing organizational accounts can be set up if needed. Passkeys offer another way to sign in."],
    ], caveat: "Available features depend on your software version, selected modules and setup. Controlling devices also requires suitable hardware." },
    audiences: { title: "Different spaces. Familiar challenges.", cases: [
      ["Makerspaces & fab labs", "Many members, different levels of experience and shared equipment. Clear handovers instead of separate lists."],
      ["Universities & research", "Changing courses and projects. Keep track of safety briefings, roles and supervision."],
      ["Industry & training", "Machine pools and training areas with clear responsibilities and documented usage."],
    ] },
    newsletter: { title: "News for your workshop.", text: "Occasional updates on Attraccess and running workshops with shared equipment.", email: "Email address", name: "Name (optional)", consent: "I consent to my details being processed for the newsletter.", submit: "Keep me updated", note: "Confirmation by email. Unsubscribe at any time." },
  },
} as const;
