// Regenerate the progressive-enhancement stills from the actual workshop, not separate artwork.
import { mkdir, rm, stat } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { resolve } from "node:path";
import puppeteer from "puppeteer";
import { createServer } from "vite";

const root = fileURLToPath(new URL("..", import.meta.url));
const output = resolve(root, "public/workshop");
const server = await createServer({ root, server: { port: 4191, strictPort: true } });
await server.listen();
let browser;
try {
  browser = await puppeteer.launch({ headless: "shell", executablePath: process.env.PUPPETEER_EXECUTABLE_PATH || undefined, args: ["--no-sandbox", "--enable-unsafe-swiftshader"] });
  const page = await browser.newPage();
  await page.setViewport({ width: 1440, height: 1000, deviceScaleFactor: 1 });
  await page.evaluateOnNewDocument(() => { localStorage.setItem("language", "en"); localStorage.setItem("theme", "light"); });
  await page.goto("http://localhost:4191", { waitUntil: "networkidle2" });
  await page.waitForSelector(".workshop-visual.is-ready", { timeout: 30000 });
  await mkdir(output, { recursive: true });
  const stops = { overview: "system", identify: "loop", evaluate: "permissions", apply: "release", record: "sessions", connect: "operations", pilot: "pilot" };
  let total = 0;
  let count = 0;
  async function capture(view, name = view) {
    await page.waitForFunction((view) => {
      const scene = document.querySelector(".workshop-canvas");
      return scene?.dataset.story === view && scene.dataset.settled === "true";
    }, { timeout: 30000 }, name);
    const canvas = await page.$(".workshop-canvas canvas");
    const path = resolve(output, `${name}.webp`);
    // Hide the paper behind the alpha canvas only for the screenshot.
    const transparent = await page.addStyleTag({ content: "html, body, #root, .workshop-page, .workshop-stage { background: transparent !important; } .workshop-coordinate { visibility: hidden; }" });
    await canvas.screenshot({ path, type: "webp", quality: 85, omitBackground: true });
    await transparent.evaluate((style) => style.remove());
    await transparent.dispose();
    const size = (await stat(path)).size;
    total += size;
    count++;
    console.log(`${name}.webp: ${(size / 1024).toFixed(0)} kB`);
  }
  for (const [view, anchor] of Object.entries(stops)) {
    await page.click(`.workshop-chapters__links a[href="#${anchor}"]`);
    await capture(view);
  }
  async function chapter(anchor) { await page.click(`.workshop-chapters__links a[href="#${anchor}"]`); }
  async function action(name) { await page.click(`[data-action="${name}"]`); }
  await chapter("loop");
  await action("tap-card");
  await capture("identify", "identify-identified");
  await action("show-supervision");
  await capture("identify", "identify-supervision");
  await action("reset-identity");
  await chapter("permissions");
  await action("check-accessory");
  await capture("evaluate", "evaluate-checked");
  await action("submit-check");
  await capture("evaluate", "evaluate-submitted");
  await action("reset-check");
  await chapter("release");
  await action("toggle-automation");
  await capture("apply", "apply-automation");
  await action("toggle-automation");
  await chapter("sessions");
  await action("clean-workspace");
  await capture("record", "record-cleaned");
  await action("end-session");
  await capture("record", "record-form");
  await action("handoff-answer");
  await capture("record", "record-form-checked");
  await action("confirm-handoff");
  await capture("record", "record-confirmed");
  await action("reset-handoff");
  await chapter("operations");
  await action("open-report");
  await action("report-problem");
  await capture("connect", "connect-reported");
  await action("start-maintenance");
  await capture("connect", "connect-active");
  await action("complete-maintenance");
  await capture("connect", "connect-resolved");
  await action("reset-maintenance");
  await page.click('.workshop-chapters__links a[href="#system"]');
  await page.waitForSelector(".workshop-machines", { visible: true });
  for (const [index, view] of ["table-saw", "bandsaw", "cnc"].entries()) {
    await page.click(`.workshop-machines button:nth-child(${index + 2})`);
    await capture(view);
  }
  // Remove only the known obsolete illustrations generated by the previous permission-only tour.
  for (const view of ["evaluate", "apply", "table-saw", "bandsaw", "cnc"]) {
    for (const scenario of ["training", "maintenance"]) await rm(resolve(output, `${view}-${scenario}.webp`), { force: true });
  }
  console.log(`Generated ${count} stills: ${(total / 1024).toFixed(0)} kB total.`);

  if (process.env.WORKSHOP_ARTIFACT_DIR) {
    const dir = process.env.WORKSHOP_ARTIFACT_DIR;
    await page.click('.workshop-chapters__links a[href="#system"]');
    await page.waitForFunction(() => document.querySelector('.workshop-canvas[data-view="overview"]')?.dataset.settled === "true");
    await page.screenshot({ path: resolve(dir, "workshop-desktop.png") });
    await page.click('.workshop-chapters__links a[href="#permissions"]');
    await page.waitForFunction(() => document.querySelector('.workshop-canvas[data-view="evaluate"]')?.dataset.settled === "true");
    await page.screenshot({ path: resolve(dir, "workshop-permissions.png") });
    await chapter("sessions");
    await page.waitForFunction(() => document.querySelector('.workshop-canvas[data-story="record"]')?.dataset.settled === "true");
    await page.screenshot({ path: resolve(dir, "workshop-handoff-before.png") });
    await action("clean-workspace");
    await page.waitForFunction(() => document.querySelector('.workshop-canvas[data-story="record-cleaned"]')?.dataset.settled === "true");
    await page.screenshot({ path: resolve(dir, "workshop-handoff-after.png") });
    await page.click('.prototype-header__tools > button:nth-child(2)');
    await page.screenshot({ path: resolve(dir, "workshop-dark.png") });
    await page.setViewport({ width: 390, height: 844, deviceScaleFactor: 1, isMobile: true, hasTouch: true });
    await page.goto("http://localhost:4191", { waitUntil: "networkidle2" });
    await page.waitForSelector(".workshop-visual.is-ready");
    await page.screenshot({ path: resolve(dir, "workshop-mobile.png") });
    await page.click('button[aria-label="Auf Deutsch wechseln"]');
    await page.screenshot({ path: resolve(dir, "workshop-mobile-de.png") });
    await page.click('.workshop-motion');
    await page.screenshot({ path: resolve(dir, "workshop-mobile-static.png") });
    await page.setViewport({ width: 844, height: 390, deviceScaleFactor: 1, isMobile: true, hasTouch: true });
    await page.screenshot({ path: resolve(dir, "workshop-landscape.png") });
  }
} finally {
  await browser?.close();
  await server.close();
}
